### PR TITLE
Private toggle for classes

### PR DESCRIPTION
**Pull request by Gaurav0**
Issue #11

### CODE REVIEW

**Comment by Gaurav0** [comment]
Screen Capture:

show private toggle

**Comment by fivetanley** [comment]
I'll have to give this a shot against the production db. I was thinking we could do the public/private filtering on the backend for performance reasons and have public/private be two relationships. What do you think about that @Gaurav0?

**Comment by Gaurav0** [comment]
Absolutely makes sense. How do I get the latest db?

**Comment by fivetanley** [comment]
Sorry for the delay! They are now in the db for all versions here. https://fivetanley.cloudant.com/docs/project-version-ember-2.5.1

**Comment by fivetanley** [comment]
I think we could add a `publicClasses` and `privateClasses` relationship on the `ProjectVersion` model now

**Comment by Gaurav0** [comment]
See PR #48

**Pull request closed without merging**
