### PR TITLE
Setting up collapsible classes list

### LINKED ISSUE #24: Classes list should expand/unexpand like on the guides site
For example: https://guides.emberjs.com/v2.4.0/

Starts off closed:

When clicked, opens:

On the guides site, there's a neat little animation that I'm guessing is done by using a CSS transition.

This would be a great component! If you can't find something that works off the shelf (**that also works in fastboot**), unit tests would be great. It would also be great if we could make this accessible (cc @Robdel12)

### PR DESCRIPTION
**Pull request by acorncom**
Fixes #24

### CODE REVIEW

**Comment by acorncom** [comment]
Tests still need to be written.  And ideally animations would be nicer than they are right now ...

**Comment by acorncom** [comment]
@fivetanley Looks like this is ready to go

**Comment by fivetanley** [comment]
@acorncom this looks good, can you fix the merge conflicts when you have a chance? sorry for the late response.

**Comment by acorncom** [comment]
@fivetanley Updated here.  Re: late response, no problem, we all needed a bit of a breather post conference ;-)

**Pull request merged**
